/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{html,ts}',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        headline: ['Inter'],
        display: ['Inter'],
        body: ['Inter'],
        label: ['Inter'],
      },
      colors: {
        'titanium-graphite': '#1a1a1a',
        'titanium-light': '#f4f4f4',
        'titanium-accent': '#e5e7eb',
        secondary: '#64748b',
        'error-container': '#fee2e2',
        'surface-container-lowest': '#ffffff',
        'secondary-fixed': '#e2e8f0',
        'on-surface': '#0f172a',
        'primary-fixed-dim': '#b6c9dd',
        'surface-bright': '#ffffff',
        'inverse-on-surface': '#f8fafc',
        outline: '#94a3b8',
        'surface-dim': '#f7f7f7',
        'surface-container-highest': '#cbd5e1',
        'on-secondary-fixed': '#0f172a',
        tertiary: '#513822',
        primary: '#455768',
        'on-error': '#ffffff',
        'on-primary-fixed': '#0a1d2c',
        'secondary-container': '#f1f5f9',
        'inverse-surface': '#1e293b',
        'surface-variant': '#f1f5f9',
        'inverse-primary': '#b6c9dd',
        'on-primary-container': '#1e293b',
        'on-tertiary-fixed-variant': '#5c412a',
        'on-primary-fixed-variant': '#374959',
        'outline-variant': '#e2e8f0',
        error: '#ef4444',
        'surface-container': '#f1f5f9',
        'tertiary-fixed-dim': '#e5bfa1',
        'tertiary-container': '#ffdcc1',
        'on-tertiary': '#ffffff',
        'on-secondary-container': '#334155',
        background: '#f7f7f7',
        'secondary-fixed-dim': '#cbd5e1',
        'on-tertiary-container': '#2b1704',
        'tertiary-fixed': '#ffdcc1',
        'surface-container-high': '#e2e8f0',
        'on-primary': '#ffffff',
        'surface-tint': '#455768',
        surface: '#ffffff',
        'on-secondary': '#ffffff',
        'on-error-container': '#991b1b',
        'on-surface-variant': '#475569',
        'surface-container-low': '#f8fafc',
        'primary-fixed': '#d1e5f9',
        'on-secondary-fixed-variant': '#475569',
        'on-background': '#0f172a',
        'on-tertiary-fixed': '#2b1704',
        'primary-container': '#e2e8f0',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      maxWidth: {
        'container': '1440px',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
};
